<?php

/**
 * @file
 * Functions to support styling Admin toolbar.
 */

use Drupal\Component\Utility\Xss;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function adminimal_admin_toolbar_preprocess_html(&$variables) {

  // Add adminimal-admin-toolbar class to the body.
  $variables['attributes']['class'][] = 'adminimal-admin-toolbar';

}

function adminimal_admin_toolbar_page_attachments_alter(array &$page) {
  dpm($page);
  $page['#attached']['library'][] = 'adminimal_admin_toolbar/adminimal-admin-toolbar';
}
